### ISSUE TITLE
UpdateOptions.Validate clashes with Validate() method generated by protoc-gen-validate

### ISSUE THREAD

**Issue by simon0191** [cludden/protoc-gen-go-temporal#29]
The Validate field in UpdateOptions clashes with the Validate method generated by the buf.build/envoyproxy/protoc-gen-validate plugin.

Since envoyproxy/protoc-gen-validate is a very popular plugin, I think it'd be good to rename that field.

![image](https://github.com/cludden/protoc-gen-go-temporal/assets/1335661/ed0ed695-d803-483f-9b8b-a97896fc9acc)

**Comment by cludden** [comment]
Are you able to share any more details about the issue you're facing? It's unclear from the image shared where the `UpdateOptions` struct definition and corresponding `func(m *UpdateOptions) Validate() error {}` method definition originate from.

**Comment by cludden** [comment]
I haven't been able to replicate this, closing for now due to no response, feel free to reopen if you're still running into issues 🙇
