### ISSUE TITLE
Generating standalone activities without workflows

### ISSUE THREAD

**Issue by ZloyDyadka** [cludden/protoc-gen-go-temporal#38]
In many cases, Activities are designed to be atomic units of work that can be invoked independently or as part of multiple Workflows. The current limitation necessitates the creation of a Workflow even when the use case does not require one, resulting in additional, unnecessary code which does not serve any functional purpose for the intended standalone use of Activities.

**Comment by adrianlop** [comment]
this is already supported, you don't need to define a workflow. example:
```
rpc MyActivity(MyActivityRequest) returns (MyActivityResponse) {
  option (temporal.v1.activity) = {
    heartbeat_timeout: { seconds: 60 }
    schedule_to_close_timeout: { seconds: 3600 }
  };
}
```

**Comment by ZloyDyadka** [comment]
> this is already supported, you don't need to define a workflow. example:
> 
> ```
> rpc MyActivity(MyActivityRequest) returns (MyActivityResponse) {
>   option (temporal.v1.activity) = {
>     heartbeat_timeout: { seconds: 60 }
>     schedule_to_close_timeout: { seconds: 3600 }
>   };
> }
> ```

Yes, but the code will be generated for Workflow.
Code: https://github.com/cludden/protoc-gen-go-temporal/blob/main/internal/plugin/service.go#L431

**Comment by adrianlop** [comment]
not really, L431-432 will generate these two functions for the **Client**:
```
	// CancelWorkflow requests cancellation of an existing workflow execution
	CancelWorkflow(ctx context.Context, workflowID string, runID string) error
	// TerminateWorkflow an existing workflow execution
	TerminateWorkflow(ctx context.Context, workflowID string, runID string, reason string, details ...interface{}) error
```

which have nothing to do with Activities (see [this file](https://github.com/cludden/protoc-gen-go-temporal/blob/main/internal/plugin/activities.go) instead)

**Comment by cludden** [comment]
@adrianlop is correct, the linked code is related to the generated client, which is orthogonal to the generated activity helpers. While it's true that the current implementation generates unnecessary code for a service with only activities defined, changing that behavior belongs to a larger class of general optimization work to tackle in the future. I have gone ahead and added to tests to verify that the generated code for a service with only activities defined behaves as expected.
