### ISSUE TITLE
Some features & breaking changes

### ISSUE THREAD

**Issue by ZloyDyadka** [cludden/protoc-gen-go-temporal#5]
Hello! I have a couple of suggestions for improvement, but they will break the current API.

1. Add synchronous and asynchronous access to Activity.
This would eliminate the need to use Future when it's not necessary and reduce the amount of code lines.
2. Abandon the opts parameter, as the user can pass them through GetActivityOptions, which we can extract from the context. Alternatively, switch to something like configurator functions (optional) in the format of ActivityOpt.
This would also allow not to constantly pass nils and not clutter the code.
3. Change the order of arguments: ctx, args, opts (I think the configuration should always be the last arguments).
4. Divide the LocalActivity call method into two, one by name and the other by function. This will prevent overloading one method. Example: SomeActivity3LocalByName, SomeActivity3LocalByFunc.
5. Add same access methods for Workflow?

Below I provided an example for the 3rd points:
```
// SomeActivity3 does some activity thing.
func SomeActivity3Local(ctx workflow.Context, fn func(context.Context, *SomeActivity3Request) (*SomeActivity3Response, error), req *SomeActivity3Request) (*SomeActivity3Response, error) {
	future := AsyncSomeActivity3Local(ctx, req, fn)
	return future.Get(ctx)
}

// SomeActivity3 does some activity thing.
func SomeActivity3(ctx workflow.Context, req *SomeActivity3Request) (*SomeActivity3Response, error) {
	future := AsyncSomeActivity3(ctx, req)
	return future.Get(ctx)
}

// SomeActivity3 does some activity thing.
func AsyncSomeActivity3(ctx workflow.Context, req *SomeActivity3Request) *SomeActivity3Future {
	opts := workflow.GetActivityOptions(ctx)
	if opts.RetryPolicy == nil {
		opts.RetryPolicy = &temporal.RetryPolicy{MaximumAttempts: int32(5)}
	}
	if opts.StartToCloseTimeout == 0 {
		opts.StartToCloseTimeout = 10000000000 // 10s
	}
	ctx = workflow.WithActivityOptions(ctx, opts)
	return &SomeActivity3Future{Future: workflow.ExecuteActivity(ctx, SomeActivity3ActivityName, req)}
}

// SomeActivity3 does some activity thing.
func AsyncSomeActivity3Local(ctx workflow.Context, req *SomeActivity3Request, fn func(context.Context, *SomeActivity3Request) (*SomeActivity3Response, error)) *SomeActivity3Future {
	opts := workflow.GetLocalActivityOptions(ctx)
	if opts.RetryPolicy == nil {
		opts.RetryPolicy = &temporal.RetryPolicy{MaximumAttempts: int32(5)}
	}
	if opts.StartToCloseTimeout == 0 {
		opts.StartToCloseTimeout = 10000000000 // 10s
	}
	ctx = workflow.WithLocalActivityOptions(ctx, opts)
	var activity any
	if fn == nil {
		activity = SomeActivity3ActivityName
	} else {
		activity = fn
	}
	return &SomeActivity3Future{Future: workflow.ExecuteLocalActivity(ctx, activity, req)}
}
```

**Comment by cludden** [comment]
These are great suggestions, and timely, as after some heavy internal usage, we've started to investigate other potential breaking changes [here](https://github.com/cludden/protoc-gen-go-temporal/compare/cludden/v1) (which covers your proposal 2 and 3, by specifically making options args an optional/variadic. We'll definitely consider converting these options to "configurator functions" to better support future extension

**Comment by ZloyDyadka** [comment]
@cludden Oh, I didn't know about the v1 branch :(
I've already started working on Activities Sync\Async, but I took from main, so I'll transfer the changes from v1 and integrate them into my branch.
Once I'm done, I'll create an MR with Activities, and if that's okay, then I'll do something similar for Workflow\Signals.
https://github.com/ZloyDyadka/protoc-gen-go-temporal/compare/main...ZloyDyadka:protoc-gen-go-temporal:sync-asyc-activities

**Comment by cludden** [comment]
I've moved these proposals to the checklist for [v1](#7) and will track their status there. Thanks again for the suggestions!
