### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by Smithx10** [cludden/protoc-gen-go-temporal#79]
I have a sqlc-plugin that generates protobuf via string annotations above sql.

While importing the pb.go Structs to be used with protobuilder,  I noticed the Enum didn't completely match up with the documentation.

How does this work?  

``` go 
// enumerates all defined patch versions
type Patch_Version int32

const (
	Patch_PV_UNSPECIFIED Patch_Version = 0
	// wraps expression evaluation in local activities within workflow contexts
	// details: https://cludden.github.io/protoc-gen-go-temporal/docs/guides/fix-versions#fix_version_64_expression_evaluation_local_activity
	Patch_PV_64 Patch_Version = 1
)

// Enum value maps for Patch_Version.
var (
	Patch_Version_name = map[int32]string{
		0: "PV_UNSPECIFIED",
		1: "PV_64",
	}
	Patch_Version_value = map[string]int32{
		"PV_UNSPECIFIED": 0,
		"PV_64":          1,
	}
)

```

``` proto
service Example {
  option (temporal.v1.service) = {
    patches: [
      { version: PV_62, mode: PV_REMOVED },
      { version: PV_63, mode: PV_MARKER },
      { version: PV_64, mode: PV_ENABLED },
      { version: PV_65, mode: PV_DISABLED }
    ]
  };
}
```

**Comment by cludden** [comment]
Hi @Smithx10, the documentation is more for illustrative purposes, and currently contains a bug (i.e. modes should be prefixed with `PVM_`, see the patch message definition here[).](https://github.com/cludden/protoc-gen-go-temporal/blob/main/proto/temporal/v1/temporal.proto#L97-L126) At the moment, only one patch version exists in a released version of this plugin. There is a potential second patch version being considered [here](https://github.com/cludden/protoc-gen-go-temporal/pull/77).
